#! /usr/bin/env sh

if [ "$1" ]; then
    echo "$1 is my brother!!"
elif [ "$1" = "nanaumi" ]; then
    echo "$1 is not my brother..."
else
    echo "No arguments. Who are you...?"
    echo "exited with code 1."
    exit 1
fi
